# Generated by Django 5.1.1 on 2024-11-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rental_end_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
