# Generated by Django 5.1.1 on 2024-11-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicle_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(choices=[('Carro', 'Car'), ('Moto', 'Motorcycle')], default='Carro', max_length=10),
        ),
    ]
