# Generated by Django 5.1.1 on 2025-11-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(default='avatars/default.png', help_text='Avatar do usuário', upload_to='avatars/')),
                ('name', models.CharField(help_text='Nome completo do usuário', max_length=100)),
                ('email', models.EmailField(help_text='Email do usuário (usado para login)', max_length=255, unique=True)),
                ('cpf', models.CharField(help_text='CPF do usuário', max_length=14, unique=True)),
                ('address', models.CharField(blank=True, help_text='Endereço do usuário', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Telefone do usuário', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Indica se o usuário é superusuário (admin)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
