# Generated by Django 5.1.1 on 2025-11-14 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Data de início do aluguel')),
                ('end_date', models.DateField(blank=True, help_text='Data de devolução do veículo', null=True)),
                ('returned', models.BooleanField(default=False, help_text='Indica se o veículo foi devolvido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Cliente que realizou o aluguel', on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='client.client')),
                ('vehicle', models.ForeignKey(help_text='Veículo alugado', on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
                'ordering': ['-start_date'],
            },
        ),
    ]
