# Generated by Django 5.1.1 on 2025-11-14 01:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type_vehicle', models.CharField(choices=[('Carro', 'Car'), ('Moto', 'Motorcycle')], default='Carro', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
